export const countries = [
	{
		code: 'PL',
		name: 'Poland',
		flag: 'https://media-2.api-sports.io/flags/pl.svg',
	},
	{
		code: 'GB',
		name: 'England',
		flag: 'https://media-2.api-sports.io/flags/gb.svg',
	},
	{
		code: 'ES',
		name: 'Spain',
		flag: 'https://media-2.api-sports.io/flags/es.svg',
	},
	{
		code: 'DE',
		name: 'Germany',
		flag: 'https://media-2.api-sports.io/flags/de.svg',
	},
	{
		code: 'IT',
		name: 'Italy',
		flag: 'https://media-2.api-sports.io/flags/it.svg',
	},
	{
		code: 'FR',
		name: 'France',
		flag: 'https://media-2.api-sports.io/flags/fr.svg',
	},
	{
		code: 'NL',
		name: 'Netherlands',
		flag: 'https://media-2.api-sports.io/flags/nl.svg',
	},
	{
		code: 'PT',
		name: 'Portugal',
		flag: 'https://media-2.api-sports.io/flags/pt.svg',
	},
	{
		code: 'BE',
		name: 'Belgium',
		flag: 'https://media-2.api-sports.io/flags/be.svg',
	},
	{
		code: 'GR',
		name: 'Greece',
		flag: 'https://media-2.api-sports.io/flags/gr.svg',
	},
];

export const leagues = [
	{
		id: 106,
		country: 'Poland',
		flag: 'https://media-2.api-sports.io/flags/pl.svg',
		name: 'Ekstraklasa',
		logo: 'https://media-1.api-sports.io/football/leagues/106.png',
	},
	{
		id: 107,
		country: 'Poland',
		flag: 'https://media-2.api-sports.io/flags/pl.svg',
		name: 'I Liga',
		logo: 'https://media-1.api-sports.io/football/leagues/107.png',
	},
	{
		id: 39,
		country: 'England',
		flag: 'https://media-2.api-sports.io/flags/gb.svg',
		name: 'Premier League',
		logo: 'https://media-1.api-sports.io/football/leagues/39.png',
	},
	{
		id: 40,
		country: 'England',
		flag: 'https://media-2.api-sports.io/flags/gb.svg',
		name: 'Championship',
		logo: 'https://media-1.api-sports.io/football/leagues/40.png',
	},
	{
		id: 140,
		country: 'Spain',
		flag: 'https://media-2.api-sports.io/flags/es.svg',
		name: 'La Liga',
		logo: 'https://media-1.api-sports.io/football/leagues/140.png',
	},
	{
		id: 141,
		country: 'Spain',
		flag: 'https://media-2.api-sports.io/flags/es.svg',
		name: 'Segunda División',
		logo: 'https://media-1.api-sports.io/football/leagues/141.png',
	},
	{
		id: 78,
		country: 'Germany',
		flag: 'https://media-2.api-sports.io/flags/de.svg',
		name: 'Bundesliga',
		logo: 'https://media-1.api-sports.io/football/leagues/78.png',
	},
	{
		id: 79,
		country: 'Germany',
		flag: 'https://media-2.api-sports.io/flags/de.svg',
		name: '2. Bundesliga',
		logo: 'https://media-1.api-sports.io/football/leagues/79.png',
	},
	{
		id: 135,
		country: 'Italy',
		flag: 'https://media-2.api-sports.io/flags/it.svg',
		name: 'Serie A',
		logo: 'https://media-1.api-sports.io/football/leagues/135.png',
	},
	{
		id: 136,
		country: 'Italy',
		flag: 'https://media-2.api-sports.io/flags/it.svg',
		name: 'Serie B',
		logo: 'https://media-1.api-sports.io/football/leagues/136.png',
	},
	{
		id: 61,
		country: 'France',
		flag: 'https://media-2.api-sports.io/flags/fr.svg',
		name: 'Ligue 1',
		logo: 'https://media-1.api-sports.io/football/leagues/61.png',
	},
	{
		id: 62,
		country: 'France',
		flag: 'https://media-2.api-sports.io/flags/fr.svg',
		name: 'Ligue 2',
		logo: 'https://media-1.api-sports.io/football/leagues/62.png',
	},
	{
		id: 88,
		country: 'Netherlands',
		flag: 'https://media-2.api-sports.io/flags/nl.svg',
		name: 'Eredivisie',
		logo: 'https://media-1.api-sports.io/football/leagues/88.png',
	},
	{
		id: 144,
		country: 'Belgium',
		flag: 'https://media-2.api-sports.io/flags/be.svg',
		name: 'Jupiler Pro League',
		logo: 'https://media-1.api-sports.io/football/leagues/144.png',
	},
	{
		id: 94,
		country: 'Portugal',
		flag: 'https://media-2.api-sports.io/flags/pt.svg',
		name: 'Primeira Liga',
		logo: 'https://media-1.api-sports.io/football/leagues/94.png',
	},
	{
		id: 198,
		country: 'Greece',
		flag: 'https://media-2.api-sports.io/flags/gr.svg',
		name: 'Football League',
		logo: 'https://media-1.api-sports.io/football/leagues/198.png',
	},
];
