export const countries = [
	{
		code: 'PL',
		name: 'Poland',
		flag: 'https://media-2.api-sports.io/flags/pl.svg',
	},
	{
		code: 'GB',
		name: 'England',
		flag: 'https://media-2.api-sports.io/flags/gb.svg',
	},
	{
		code: 'ES',
		name: 'Spain',
		flag: 'https://media-2.api-sports.io/flags/es.svg',
	},
	{
		code: 'DE',
		name: 'Germany',
		flag: 'https://media-2.api-sports.io/flags/de.svg',
	},
	{
		code: 'IT',
		name: 'Italy',
		flag: 'https://media-2.api-sports.io/flags/it.svg',
	},
	{
		code: 'FR',
		name: 'France',
		flag: 'https://media-2.api-sports.io/flags/fr.svg',
	},
];

export const leagues = [
	{
		id: 106,
		country: 'Poland',
		flag: 'https://media-2.api-sports.io/flags/pl.svg',
		name: 'Ekstraklasa',
		logo: 'https://media-1.api-sports.io/football/leagues/106.png',
	},
	{
		id: 107,
		country: 'Poland',
		flag: 'https://media-2.api-sports.io/flags/pl.svg',
		name: 'I Liga',
		logo: 'https://media-1.api-sports.io/football/leagues/107.png',
	},
	{
		id: 39,
		country: 'England',
		flag: 'https://media-2.api-sports.io/flags/gb.svg',
		name: 'Premier League',
		logo: 'https://media-1.api-sports.io/football/leagues/39.png',
	},
	{
		id: 40,
		country: 'England',
		flag: 'https://media-2.api-sports.io/flags/gb.svg',
		name: 'Championship',
		logo: 'https://media-1.api-sports.io/football/leagues/40.png',
	},
	{
		id: 140,
		country: 'Spain',
		flag: 'https://media-2.api-sports.io/flags/es.svg',
		name: 'La Liga',
		logo: 'https://media-1.api-sports.io/football/leagues/140.png',
	},
	{
		id: 141,
		country: 'Spain',
		flag: 'https://media-2.api-sports.io/flags/es.svg',
		name: 'Segunda División',
		logo: 'https://media-1.api-sports.io/football/leagues/141.png',
	},
	{
		id: 78,
		country: 'Germany',
		flag: 'https://media-2.api-sports.io/flags/de.svg',
		name: 'Bundesliga',
		logo: 'https://media-1.api-sports.io/football/leagues/78.png',
	},
	{
		id: 79,
		country: 'Germany',
		flag: 'https://media-2.api-sports.io/flags/de.svg',
		name: '2. Bundesliga',
		logo: 'https://media-1.api-sports.io/football/leagues/79.png',
	},
	{
		id: 135,
		country: 'Italy',
		flag: 'https://media-2.api-sports.io/flags/it.svg',
		name: 'Serie A',
		logo: 'https://media-1.api-sports.io/football/leagues/135.png',
	},
	{
		id: 136,
		country: 'Italy',
		flag: 'https://media-2.api-sports.io/flags/it.svg',
		name: 'Serie B',
		logo: 'https://media-1.api-sports.io/football/leagues/136.png',
	},
	{
		id: 61,
		country: 'France',
		flag: 'https://media-2.api-sports.io/flags/fr.svg',
		name: 'Ligue 1',
		logo: 'https://media-1.api-sports.io/football/leagues/61.png',
	},
	{
		id: 62,
		country: 'France',
		flag: 'https://media-2.api-sports.io/flags/fr.svg',
		name: 'Ligue 2',
		logo: 'https://media-1.api-sports.io/football/leagues/62.png',
	},
	{
		id: 277,
		country: 'Kenya',
		flag: 'https://media-2.api-sports.io/flags/ke.svg',
		name: 'Super League',
		logo: 'https://media-1.api-sports.io/football/leagues/277.png',
	},
	{
		id: 636,
		country: 'Turkmenistan',
		flag: 'https://media-2.api-sports.io/flags/tm.svg',
		name: 'Ýokary Liga',
		logo: 'https://media-1.api-sports.io/football/leagues/636.png',
	},
	{
		id: 339,
		country: 'Guatemala',
		flag: 'https://media-2.api-sports.io/flags/gt.svg',
		name: 'Liga Nacional',
		logo: 'https://media-1.api-sports.io/football/leagues/339.png',
	},
	{
		id: 418,
		country: 'Azerbaijan',
		flag: 'https://media-2.api-sports.io/flags/az.svg',
		name: 'Birinci Dasta',
		logo: 'https://media-1.api-sports.io/football/leagues/418.png',
	},
	{
		id: 169,
		country: 'China',
		flag: 'https://media-2.api-sports.io/flags/cn.svg',
		name: 'Super League',
		logo: 'https://media-1.api-sports.io/football/leagues/169.png',
	},
	{
		id: 584,
		country: 'Libya',
		flag: 'https://media-2.api-sports.io/flags/ly.svg',
		name: 'Premier League',
		logo: 'https://media-1.api-sports.io/football/leagues/584.png',
	},
	{
		id: 667,
		country: 'World',
		flag: null,
		name: 'Friendlies Club',
		logo: 'https://media-1.api-sports.io/football/leagues/667.png',
	},
	{
		id: 2,
		country: 'World',
		flag: null,
		name: 'Champions League',
		logo: 'https://media-1.api-sports.io/football/leagues/2.png',
	},
	{
		id: 188,
		country: 'Australia',
		flag: 'https://media-2.api-sports.io/flags/au.svg',
		name: 'A-League',
		logo: 'https://media-1.api-sports.io/football/leagues/188.png',
	},
];
