export const standingsChampionship = {
	get: 'standings',
	parameters: {
		league: '40',
		season: '2022',
	},
	errors: [],
	results: 1,
	paging: {
		current: 1,
		total: 1,
	},
	response: [
		{
			league: {
				id: 40,
				name: 'Championship',
				country: 'England',
				logo: 'https://media-4.api-sports.io/football/leagues/40.png',
				flag: 'https://media-6.api-sports.io/flags/gb.svg',
				season: 2022,
				standings: [
					[
						{
							rank: 1,
							team: {
								id: 44,
								name: 'Burnley',
								logo: 'https://media-4.api-sports.io/football/teams/44.png',
							},
							points: 47,
							goalsDiff: 22,
							group: 'Championship',
							form: 'WWWLW',
							status: 'same',
							description: 'Promotion - Premier League',
							all: {
								played: 23,
								win: 13,
								draw: 8,
								lose: 2,
								goals: {
									for: 46,
									against: 24,
								},
							},
							home: {
								played: 12,
								win: 8,
								draw: 4,
								lose: 0,
								goals: {
									for: 26,
									against: 11,
								},
							},
							away: {
								played: 11,
								win: 5,
								draw: 4,
								lose: 2,
								goals: {
									for: 20,
									against: 13,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 2,
							team: {
								id: 62,
								name: 'Sheffield Utd',
								logo: 'https://media-4.api-sports.io/football/teams/62.png',
							},
							points: 44,
							goalsDiff: 18,
							group: 'Championship',
							form: 'WWWLW',
							status: 'same',
							description: 'Promotion - Premier League',
							all: {
								played: 23,
								win: 13,
								draw: 5,
								lose: 5,
								goals: {
									for: 38,
									against: 20,
								},
							},
							home: {
								played: 11,
								win: 6,
								draw: 3,
								lose: 2,
								goals: {
									for: 23,
									against: 11,
								},
							},
							away: {
								played: 12,
								win: 7,
								draw: 2,
								lose: 3,
								goals: {
									for: 15,
									against: 9,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 3,
							team: {
								id: 67,
								name: 'Blackburn',
								logo: 'https://media-6.api-sports.io/football/teams/67.png',
							},
							points: 39,
							goalsDiff: 1,
							group: 'Championship',
							form: 'WLLWL',
							status: 'same',
							description: 'Promotion - Championship (Play Offs)',
							all: {
								played: 23,
								win: 13,
								draw: 0,
								lose: 10,
								goals: {
									for: 27,
									against: 26,
								},
							},
							home: {
								played: 11,
								win: 8,
								draw: 0,
								lose: 3,
								goals: {
									for: 18,
									against: 11,
								},
							},
							away: {
								played: 12,
								win: 5,
								draw: 0,
								lose: 7,
								goals: {
									for: 9,
									against: 15,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 4,
							team: {
								id: 38,
								name: 'Watford',
								logo: 'https://media-5.api-sports.io/football/teams/38.png',
							},
							points: 37,
							goalsDiff: 8,
							group: 'Championship',
							form: 'WDDWL',
							status: 'same',
							description: 'Promotion - Championship (Play Offs)',
							all: {
								played: 23,
								win: 10,
								draw: 7,
								lose: 6,
								goals: {
									for: 30,
									against: 22,
								},
							},
							home: {
								played: 11,
								win: 6,
								draw: 2,
								lose: 3,
								goals: {
									for: 17,
									against: 10,
								},
							},
							away: {
								played: 12,
								win: 4,
								draw: 5,
								lose: 3,
								goals: {
									for: 13,
									against: 12,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 5,
							team: {
								id: 71,
								name: 'Norwich',
								logo: 'https://media-4.api-sports.io/football/teams/71.png',
							},
							points: 35,
							goalsDiff: 5,
							group: 'Championship',
							form: 'LWLWD',
							status: 'same',
							description: 'Promotion - Championship (Play Offs)',
							all: {
								played: 23,
								win: 10,
								draw: 5,
								lose: 8,
								goals: {
									for: 30,
									against: 25,
								},
							},
							home: {
								played: 12,
								win: 5,
								draw: 3,
								lose: 4,
								goals: {
									for: 18,
									against: 14,
								},
							},
							away: {
								played: 11,
								win: 5,
								draw: 2,
								lose: 4,
								goals: {
									for: 12,
									against: 11,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 6,
							team: {
								id: 72,
								name: 'QPR',
								logo: 'https://media-6.api-sports.io/football/teams/72.png',
							},
							points: 34,
							goalsDiff: 0,
							group: 'Championship',
							form: 'WLLLL',
							status: 'same',
							description: 'Promotion - Championship (Play Offs)',
							all: {
								played: 23,
								win: 10,
								draw: 4,
								lose: 9,
								goals: {
									for: 27,
									against: 27,
								},
							},
							home: {
								played: 11,
								win: 5,
								draw: 2,
								lose: 4,
								goals: {
									for: 15,
									against: 13,
								},
							},
							away: {
								played: 12,
								win: 5,
								draw: 2,
								lose: 5,
								goals: {
									for: 12,
									against: 14,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 7,
							team: {
								id: 59,
								name: 'Preston',
								logo: 'https://media-5.api-sports.io/football/teams/59.png',
							},
							points: 34,
							goalsDiff: 0,
							group: 'Championship',
							form: 'LWLWW',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 9,
								draw: 7,
								lose: 7,
								goals: {
									for: 22,
									against: 22,
								},
							},
							home: {
								played: 12,
								win: 3,
								draw: 4,
								lose: 5,
								goals: {
									for: 7,
									against: 12,
								},
							},
							away: {
								played: 11,
								win: 6,
								draw: 3,
								lose: 2,
								goals: {
									for: 15,
									against: 10,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 8,
							team: {
								id: 54,
								name: 'Birmingham',
								logo: 'https://media-6.api-sports.io/football/teams/54.png',
							},
							points: 32,
							goalsDiff: 4,
							group: 'Championship',
							form: 'WDLDW',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 8,
								draw: 8,
								lose: 7,
								goals: {
									for: 26,
									against: 22,
								},
							},
							home: {
								played: 12,
								win: 4,
								draw: 5,
								lose: 3,
								goals: {
									for: 16,
									against: 12,
								},
							},
							away: {
								played: 11,
								win: 4,
								draw: 3,
								lose: 4,
								goals: {
									for: 10,
									against: 10,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 9,
							team: {
								id: 58,
								name: 'Millwall',
								logo: 'https://media-5.api-sports.io/football/teams/58.png',
							},
							points: 32,
							goalsDiff: 1,
							group: 'Championship',
							form: 'DLWDD',
							status: 'same',
							description: null,
							all: {
								played: 22,
								win: 9,
								draw: 5,
								lose: 8,
								goals: {
									for: 27,
									against: 26,
								},
							},
							home: {
								played: 11,
								win: 7,
								draw: 2,
								lose: 2,
								goals: {
									for: 17,
									against: 8,
								},
							},
							away: {
								played: 11,
								win: 2,
								draw: 3,
								lose: 6,
								goals: {
									for: 10,
									against: 18,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 10,
							team: {
								id: 76,
								name: 'Swansea',
								logo: 'https://media-4.api-sports.io/football/teams/76.png',
							},
							points: 32,
							goalsDiff: -2,
							group: 'Championship',
							form: 'DLDDD',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 8,
								draw: 8,
								lose: 7,
								goals: {
									for: 30,
									against: 32,
								},
							},
							home: {
								played: 11,
								win: 5,
								draw: 2,
								lose: 4,
								goals: {
									for: 15,
									against: 14,
								},
							},
							away: {
								played: 12,
								win: 3,
								draw: 6,
								lose: 3,
								goals: {
									for: 15,
									against: 18,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 11,
							team: {
								id: 53,
								name: 'Reading',
								logo: 'https://media-6.api-sports.io/football/teams/53.png',
							},
							points: 32,
							goalsDiff: -7,
							group: 'Championship',
							form: 'LWWLL',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 10,
								draw: 2,
								lose: 11,
								goals: {
									for: 26,
									against: 33,
								},
							},
							home: {
								played: 11,
								win: 7,
								draw: 1,
								lose: 3,
								goals: {
									for: 16,
									against: 11,
								},
							},
							away: {
								played: 12,
								win: 3,
								draw: 1,
								lose: 8,
								goals: {
									for: 10,
									against: 22,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 12,
							team: {
								id: 746,
								name: 'Sunderland',
								logo: 'https://media-5.api-sports.io/football/teams/746.png',
							},
							points: 31,
							goalsDiff: 5,
							group: 'Championship',
							form: 'DLWWL',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 8,
								draw: 7,
								lose: 8,
								goals: {
									for: 31,
									against: 26,
								},
							},
							home: {
								played: 11,
								win: 3,
								draw: 4,
								lose: 4,
								goals: {
									for: 14,
									against: 12,
								},
							},
							away: {
								played: 12,
								win: 5,
								draw: 3,
								lose: 4,
								goals: {
									for: 17,
									against: 14,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 13,
							team: {
								id: 70,
								name: 'Middlesbrough',
								logo: 'https://media-4.api-sports.io/football/teams/70.png',
							},
							points: 30,
							goalsDiff: 2,
							group: 'Championship',
							form: 'LWWWD',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 8,
								draw: 6,
								lose: 9,
								goals: {
									for: 32,
									against: 30,
								},
							},
							home: {
								played: 11,
								win: 4,
								draw: 5,
								lose: 2,
								goals: {
									for: 13,
									against: 11,
								},
							},
							away: {
								played: 12,
								win: 4,
								draw: 1,
								lose: 7,
								goals: {
									for: 19,
									against: 19,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 14,
							team: {
								id: 1346,
								name: 'Coventry',
								logo: 'https://media-6.api-sports.io/football/teams/1346.png',
							},
							points: 30,
							goalsDiff: 2,
							group: 'Championship',
							form: 'DLWWW',
							status: 'same',
							description: null,
							all: {
								played: 21,
								win: 8,
								draw: 6,
								lose: 7,
								goals: {
									for: 24,
									against: 22,
								},
							},
							home: {
								played: 10,
								win: 5,
								draw: 2,
								lose: 3,
								goals: {
									for: 13,
									against: 9,
								},
							},
							away: {
								played: 11,
								win: 3,
								draw: 4,
								lose: 4,
								goals: {
									for: 11,
									against: 13,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 15,
							team: {
								id: 1359,
								name: 'Luton',
								logo: 'https://media-4.api-sports.io/football/teams/1359.png',
							},
							points: 30,
							goalsDiff: 0,
							group: 'Championship',
							form: 'LDLWD',
							status: 'same',
							description: null,
							all: {
								played: 22,
								win: 7,
								draw: 9,
								lose: 6,
								goals: {
									for: 24,
									against: 24,
								},
							},
							home: {
								played: 11,
								win: 2,
								draw: 7,
								lose: 2,
								goals: {
									for: 14,
									against: 12,
								},
							},
							away: {
								played: 11,
								win: 5,
								draw: 2,
								lose: 4,
								goals: {
									for: 10,
									against: 12,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 16,
							team: {
								id: 60,
								name: 'West Brom',
								logo: 'https://media-4.api-sports.io/football/teams/60.png',
							},
							points: 29,
							goalsDiff: 4,
							group: 'Championship',
							form: 'WWWWW',
							status: 'same',
							description: null,
							all: {
								played: 22,
								win: 7,
								draw: 8,
								lose: 7,
								goals: {
									for: 29,
									against: 25,
								},
							},
							home: {
								played: 12,
								win: 4,
								draw: 4,
								lose: 4,
								goals: {
									for: 17,
									against: 14,
								},
							},
							away: {
								played: 10,
								win: 3,
								draw: 4,
								lose: 3,
								goals: {
									for: 12,
									against: 11,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 17,
							team: {
								id: 75,
								name: 'Stoke City',
								logo: 'https://media-4.api-sports.io/football/teams/75.png',
							},
							points: 29,
							goalsDiff: -4,
							group: 'Championship',
							form: 'WDLWL',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 8,
								draw: 5,
								lose: 10,
								goals: {
									for: 26,
									against: 30,
								},
							},
							home: {
								played: 11,
								win: 3,
								draw: 3,
								lose: 5,
								goals: {
									for: 13,
									against: 16,
								},
							},
							away: {
								played: 12,
								win: 5,
								draw: 2,
								lose: 5,
								goals: {
									for: 13,
									against: 14,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 18,
							team: {
								id: 56,
								name: 'Bristol City',
								logo: 'https://media-4.api-sports.io/football/teams/56.png',
							},
							points: 27,
							goalsDiff: -1,
							group: 'Championship',
							form: 'LWDDL',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 7,
								draw: 6,
								lose: 10,
								goals: {
									for: 31,
									against: 32,
								},
							},
							home: {
								played: 12,
								win: 4,
								draw: 3,
								lose: 5,
								goals: {
									for: 14,
									against: 12,
								},
							},
							away: {
								played: 11,
								win: 3,
								draw: 3,
								lose: 5,
								goals: {
									for: 17,
									against: 20,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 19,
							team: {
								id: 73,
								name: 'Rotherham',
								logo: 'https://media-5.api-sports.io/football/teams/73.png',
							},
							points: 26,
							goalsDiff: -6,
							group: 'Championship',
							form: 'LLDWL',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 6,
								draw: 8,
								lose: 9,
								goals: {
									for: 26,
									against: 32,
								},
							},
							home: {
								played: 11,
								win: 4,
								draw: 3,
								lose: 4,
								goals: {
									for: 18,
									against: 15,
								},
							},
							away: {
								played: 12,
								win: 2,
								draw: 5,
								lose: 5,
								goals: {
									for: 8,
									against: 17,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 20,
							team: {
								id: 43,
								name: 'Cardiff',
								logo: 'https://media-5.api-sports.io/football/teams/43.png',
							},
							points: 26,
							goalsDiff: -8,
							group: 'Championship',
							form: 'DDLLW',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 7,
								draw: 5,
								lose: 11,
								goals: {
									for: 20,
									against: 28,
								},
							},
							home: {
								played: 12,
								win: 4,
								draw: 3,
								lose: 5,
								goals: {
									for: 10,
									against: 11,
								},
							},
							away: {
								played: 11,
								win: 3,
								draw: 2,
								lose: 6,
								goals: {
									for: 10,
									against: 17,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 21,
							team: {
								id: 64,
								name: 'Hull City',
								logo: 'https://media-4.api-sports.io/football/teams/64.png',
							},
							points: 26,
							goalsDiff: -14,
							group: 'Championship',
							form: 'DDLWD',
							status: 'same',
							description: null,
							all: {
								played: 23,
								win: 7,
								draw: 5,
								lose: 11,
								goals: {
									for: 26,
									against: 40,
								},
							},
							home: {
								played: 12,
								win: 4,
								draw: 1,
								lose: 7,
								goals: {
									for: 12,
									against: 21,
								},
							},
							away: {
								played: 11,
								win: 3,
								draw: 4,
								lose: 4,
								goals: {
									for: 14,
									against: 19,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 22,
							team: {
								id: 1356,
								name: 'Blackpool',
								logo: 'https://media-6.api-sports.io/football/teams/1356.png',
							},
							points: 24,
							goalsDiff: -9,
							group: 'Championship',
							form: 'DDLLL',
							status: 'same',
							description: 'Relegation - League One',
							all: {
								played: 23,
								win: 6,
								draw: 6,
								lose: 11,
								goals: {
									for: 25,
									against: 34,
								},
							},
							home: {
								played: 11,
								win: 3,
								draw: 2,
								lose: 6,
								goals: {
									for: 12,
									against: 16,
								},
							},
							away: {
								played: 12,
								win: 3,
								draw: 4,
								lose: 5,
								goals: {
									for: 13,
									against: 18,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 23,
							team: {
								id: 61,
								name: 'Wigan',
								logo: 'https://media-5.api-sports.io/football/teams/61.png',
							},
							points: 24,
							goalsDiff: -11,
							group: 'Championship',
							form: 'LDWLD',
							status: 'same',
							description: 'Relegation - League One',
							all: {
								played: 23,
								win: 6,
								draw: 6,
								lose: 11,
								goals: {
									for: 23,
									against: 34,
								},
							},
							home: {
								played: 12,
								win: 2,
								draw: 3,
								lose: 7,
								goals: {
									for: 9,
									against: 20,
								},
							},
							away: {
								played: 11,
								win: 4,
								draw: 3,
								lose: 4,
								goals: {
									for: 14,
									against: 14,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
						{
							rank: 24,
							team: {
								id: 37,
								name: 'Huddersfield',
								logo: 'https://media-6.api-sports.io/football/teams/37.png',
							},
							points: 19,
							goalsDiff: -10,
							group: 'Championship',
							form: 'LLDWL',
							status: 'same',
							description: 'Relegation - League One',
							all: {
								played: 22,
								win: 5,
								draw: 4,
								lose: 13,
								goals: {
									for: 19,
									against: 29,
								},
							},
							home: {
								played: 12,
								win: 4,
								draw: 2,
								lose: 6,
								goals: {
									for: 10,
									against: 12,
								},
							},
							away: {
								played: 10,
								win: 1,
								draw: 2,
								lose: 7,
								goals: {
									for: 9,
									against: 17,
								},
							},
							update: '2022-12-19T00:00:00+00:00',
						},
					],
				],
			},
		},
	],
};
